[package]
name = "adrivehelper"
version = "1.3.0"
edition = "2021"

[dependencies]
tiny_http = "0.12"
webbrowser = "1.0"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
strip = "debuginfo"
