name: Build adrivehelper

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - name: Linux x64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: adrivehelper-linux-x64

          - name: Windows x86
            os: windows-latest
            target: i686-pc-windows-msvc
            artifact_name: adrivehelper-windows-x86.exe

          - name: macOS universal2
            os: macos-latest
            target: universal2-apple-darwin
            artifact_name: adrivehelper-macos-universal2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust target (Linux/Windows)
        if: matrix.target != 'universal2-apple-darwin'
        run: rustup target add ${{ matrix.target }}

      - name: Build (Linux)
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        working-directory: ./adrivehelper
        run: cargo build --release --target ${{ matrix.target }}

      - name: Build (Windows)
        if: matrix.target == 'i686-pc-windows-msvc'
        working-directory: ./adrivehelper
        run: |
          cargo install thunk-cli
          build.cmd

      # macOS: build x86_64 and aarch64 separately, then lipo merge
      - name: Install Rust targets (macOS)
        if: matrix.target == 'universal2-apple-darwin'
        run: |
          rustup target add aarch64-apple-darwin
          rustup target add x86_64-apple-darwin

      - name: Build macOS x86_64
        if: matrix.target == 'universal2-apple-darwin'
        working-directory: ./adrivehelper
        run: cargo build --release --target x86_64-apple-darwin

      - name: Build macOS aarch64
        if: matrix.target == 'universal2-apple-darwin'
        working-directory: ./adrivehelper
        run: cargo build --release --target aarch64-apple-darwin

      - name: Combine macOS fat binary
        if: matrix.target == 'universal2-apple-darwin'
        working-directory: ./adrivehelper
        run: |
          mkdir -p target/universal2-apple-darwin
          lipo -create \
            target/x86_64-apple-darwin/release/adrivehelper \
            target/aarch64-apple-darwin/release/adrivehelper \
            -output target/universal2-apple-darwin/adrivehelper

      - name: Upload artifact (Linux)
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            ./adrivehelper/target/${{ matrix.target }}/release/adrivehelper

      - name: Upload artifact (Windows)
        if: matrix.target == 'i686-pc-windows-msvc'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            ./adrivehelper/target/winxp_build/${{ matrix.target }}/release/adrivehelper.exe

      - name: Upload artifact (macOS universal2)
        if: matrix.target == 'universal2-apple-darwin'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ./adrivehelper/target/universal2-apple-darwin/adrivehelper
