name: Build TYSS

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update packages
        run: |
          sudo -n apt-get update
          sudo -n apt-get upgrade -y python3-pip gettext
          python3 -m pip install zopflipy --no-cache-dir --break-system-packages

      - name: Silence all git safe directory warnings
        run: git config --system --add safe.directory '*'

      - name: Checkout latest citro2d commit
        run: |
          git clone --recurse-submodules https://github.com/devkitPro/citro2d.git

      - name: Set workspace permissions
        run: chmod 777 -R "$GITHUB_WORKSPACE"

      - name: Build and install citro2d
        run: |
          cd citro2d
          catnip -T 3ds -S . -B build install

      - name: Build TYSS
        run: |
          make ADRIVE_SECRET_ID=${{ secrets.ADRIVE_SECRET_ID }} -j$(nproc)

      - uses: actions/upload-artifact@master
        with:
          name: TYSS
          path: TYSS.3dsx
          if-no-files-found: error
